baseURL = "https://rcf.uniparthenope.it/"
languageCode = "en-en"
title = "Research Computing Facilities"
theme = "hugo-theme-cleanwhite"

DefaultContentLanguage = "en"
copyright = "Research Computing Facilities - Department of Science and Technologies - University of Naples “Parthenope”"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title_404 = "Page not found :("
    image_404 = "img/404-bg.jpeg"
    [languages.en.params]
      slogan = "HPC, GPU, e Cloud Computing resources management for the CI&SS, CVPR, HPSCSmart e Neptun-IA laboratories."
      [[languages.en.params.addtional_menus]]
        title =  "User Guide"
        href =  "/en/userguide/"
      [[languages.en.params.addtional_menus]]
        title =  "Access"
        href =  "/en/access/"
      [[languages.en.params.addtional_menus]]
        title =  "Resources"
        href =  "/en/resources/"
      [[languages.en.params.addtional_menus]]
        title =  "Policy"
        href =  "/en/policy/"
      [[languages.en.params.addtional_menus]]
        title =  "Projects"
        href =  "/en/projects/"
      [[languages.en.params.addtional_menus]]
        title =  "People"
        href =  "/en/people/"
      [[languages.en.params.addtional_menus]]
        title =  "About"
        href =  "/en/about/"
      
  [languages.it]
    languageName = "Italiano"
    weight = 2
    title_404 = "pagina non trovata :("
    image_404 = "img/404-bg.jpeg"
    [languages.it.params]
      slogan = "Struttura di gestione per le risorse HPC, GPU, e Cloud Computing per laboratori CI&SS, CVPR, HPSCSmart e Neptun-IA."
      [[languages.it.params.addtional_menus]]
        title =  "Guida all'Uso"
        href =  "/it/userguide/"
      [[languages.it.params.addtional_menus]]
        title =  "Accesso"
        href =  "/it/access/"
      [[languages.it.params.addtional_menus]]
        title =  "Risorse"
        href =  "/it/resources/"
      [[languages.it.params.addtional_menus]]
        title =  "Regolamento"
        href =  "/it/policy/"
      [[languages.it.params.addtional_menus]]
        title =  "Progetti"
        href =  "/it/projects/"
      [[languages.it.params.addtional_menus]]
        title =  "Persone"
        href =  "/it/people/"
      [[languages.it.params.addtional_menus]]
        title =  "Informazioni"
        href =  "/it/about/"

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/new_purple.jpg"
  SEOTitle = "Research Computing Facilities"
  description = ""
  keyword = "raffaele, montella, high performance computing, hpc, uniparthenope, università degli studi di napoli parthenope, parthenope, dipartimento di scienze e tecnologie"
  
  friends = false
  bookmarks = true
  enableBlogPost = false

  omit_categories = false

[params.social]
  rss            = true 
  email          = "rcf@uniparthenope.it"
  github         = "https://github.com/rcf-dist"

 [[params.friend_link]]
  title = "CMMMA"
  href =  "https://app.meteo.uniparthenope.it"

  [[params.bookmark_link]]
  title =  "Dipartimento di Scienze e Tecnologie"
  href =   "http://dist.uniparthenope.it"
  [[params.bookmark_link]]
  title =  "Università degli Studi di Napoli “Parthenope”"
  href =   "http://www.uniparthenope.it"
  [[params.bookmark_link]]
  title =  "Centro per il Monitoraggio e la Modellistica Marina e Atmosferica"
  href =   "http://meteo.uniparthenope.it"
  [[params.bookmark_link]]
  title =  "HPSC SmartLab"
  href =  "http://hpsclab.uniparthenope.it"
  [[params.bookmark_link]]
  title = "CVPRLab"
  href =  "http://cvprlab.uniparthenope.it"
  [[params.bookmark_link]]
  title =  "CI&SSLab"
  href =  "http://cisslab.uniparthenope.it"
  [[params.bookmark_link]]
  title = "Neptun-IA"
  href =  "http://neptunia.uniparthenope.it"
  [[params.bookmark_link]]
  title = "HPC: Key Technologies and Tools"
  href = "https://www.consorzio-cini.it/index.php/it/laboratori-nazionali/hpc-key-technologies-and-tools"
  [[params.bookmark_link]]
  title = "Consorzio Interuniversitario Nazionale per l'Informatica"
  href = "https://www.consorzio-cini.it"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
